steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '--no-cache'
    - '-t'
    - '$_AR_HOSTNAME/$PROJECT_ID/$_PKG_NAME/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    - '.'
    - '-f'
    - 'Dockerfile'
  id: Build

- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - '$_AR_HOSTNAME/$PROJECT_ID/$_PKG_NAME/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  id: Push

- name: 'gcr.io/k8s-skaffold/skaffold'
  args:
    - skaffold
    - build
    - '--interactive=false'
    - '--file-output=/workspace/artifacts.json'
  id: Skaffold-Build

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'cat /workspace/artifacts.json'
  id: Check-Artifacts

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "$_SERVICE_NAME",
      "--region", "$_REGION",
      "--annotations", "commitId=${REVISION_ID}",
      "--build-artifacts", "/workspace/artifacts.json"
    ]
  id: Create-Release

images:
- '$_AR_HOSTNAME/$PROJECT_ID/$_PKG_NAME/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: 'AR_HOSTNAME'
  _PKG_NAME: 'PKG_NAME'
  _REPO_NAME: 'REPO_NAME'
  _SERVICE_NAME: 'SERVICE_NAME'
  _REGION: 'REGION'
  COMMIT_SHA: 'COMMIT_SHA'
  SHORT_SHA: 'SHORT_SHA'
  REVISION_ID: 'REVISION_ID'