steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '--no-cache'
    - '-t'
    - '$_AR_HOSTNAME/$PROJECT_ID/$_PKG_NAME/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    - '.'
    - '-f'
    - 'Dockerfile'
  id: Build

- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - '$_AR_HOSTNAME/$PROJECT_ID/$_PKG_NAME/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  id: Push

- name: 'gcr.io/k8s-skaffold/skaffold:v4beta10'
  args:
    - run
    - '-p'
    - gcb

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "$_SERVICE_NAME",
      "--region", "$_REGION",
      "--images", "$_AR_HOSTNAME/$PROJECT_ID/$_PKG_NAME/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
      "--annotations", "commitId=${REVISION_ID}"
    ]

images:
- '$_AR_HOSTNAME/$PROJECT_ID/$_PKG_NAME/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
