apiVersion: v1
kind: Service
metadata:
  name: vertify-skaffold-service
spec:
  selector:
    app: vertify-skaffold
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
