apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertify-skaffold
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vertify-skaffold
  template:
    metadata:
      labels:
        app: vertify-skaffold
    spec:
      containers:
      - name: vertify-skaffold
        image: nginx
        ports:
        - containerPort: 8080
