apiVersion: skaffold/v2beta29
kind: Config

profiles:
  - name: dev
    build:
      artifacts:
      - image: dev
    deploy:
      kubectl:
        manifests:
          - k8s-deployment.yaml
          - k8s-service.yaml
