apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: $_SERVICE_NAME
build:
  artifacts:
  - image: gcb
deploy:
  kubectl:
    manifests:
      - k8s-deployment.yaml
      - k8s-service.yaml
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
    deploy:
      kubectl:
        manifests:
          - k8s-deployment.yaml
          - k8s-service.yaml
