apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: example
deploy:
  helm:
    releases:
      - name: dev
        chartPath: deployments/helm

profiles:
  - name: dev
    build:
      artifacts:
      - image: example-dev
    deploy:
      kubectl:
        manifests:
          - k8s-deployment.yaml
          - k8s-service.yaml
