apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: $_SERVICE_NAME
deploy:
  kubectl:
    manifests:
      - k8s-deployment.yaml
      - k8s-service.yaml
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}